In [90]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [91]:
dfx = pd.read_csv('Datasets/Train.csv')
dfx.head

<bound method NDFrame.head of       feature_1  feature_2  feature_3  feature_4  feature_5      target
0      0.293416  -0.945599  -0.421105   0.406816   0.525662  -82.154667
1     -0.836084  -0.189228  -0.776403  -1.053831   0.597997  -48.897960
2      0.236425   0.132836  -0.147723   0.699854  -0.187364   77.270371
3      0.175312   0.143194  -0.581111  -0.122107  -1.292168   -2.988581
4     -1.693011   0.542712  -2.798729  -0.686723   1.244077  -37.596722
...         ...        ...        ...        ...        ...         ...
1595  -0.274961  -0.820634  -0.757173  -0.147555  -0.307149  -80.110012
1596  -0.076099   0.255257   0.290054   1.796036   0.340350  118.315601
1597   1.044177  -0.899206   1.730399  -1.871057   0.442520 -107.510508
1598  -1.269173  -0.005052   1.857669  -1.080365   0.736334  -47.341558
1599  -1.884000  -0.849427  -1.452270   0.488613   1.459576 -115.939003

[1600 rows x 6 columns]>

In [92]:
dfx.describe()

feature_1    feature_2    feature_3    feature_4    feature_5  \
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000   
mean      0.004114    -0.027604    -0.044459    -0.042408     0.012005   
std       0.997338     1.021776     1.011768     1.017189     0.978654   
min      -3.380125    -3.314844    -3.153118    -3.250169    -2.851707   
25%      -0.647165    -0.705030    -0.706385    -0.709504    -0.615880   
50%      -0.000360    -0.043769    -0.041272    -0.029756    -0.013527   
75%       0.682118     0.645442     0.639130     0.646290     0.650089   
max       3.287205     3.438895     3.216176     2.985410     3.321770   

            target  
count  1600.000000  
mean      0.318835  
std     110.741562  
min    -379.829794  
25%     -71.897040  
50%      -0.610665  
75%      71.226603  
max     337.643014

In [93]:
f = dfx.iloc[:, :-1]
print(f)

      feature_1  feature_2  feature_3  feature_4  feature_5
0      0.293416  -0.945599  -0.421105   0.406816   0.525662
1     -0.836084  -0.189228  -0.776403  -1.053831   0.597997
2      0.236425   0.132836  -0.147723   0.699854  -0.187364
3      0.175312   0.143194  -0.581111  -0.122107  -1.292168
4     -1.693011   0.542712  -2.798729  -0.686723   1.244077
...         ...        ...        ...        ...        ...
1595  -0.274961  -0.820634  -0.757173  -0.147555  -0.307149
1596  -0.076099   0.255257   0.290054   1.796036   0.340350
1597   1.044177  -0.899206   1.730399  -1.871057   0.442520
1598  -1.269173  -0.005052   1.857669  -1.080365   0.736334
1599  -1.884000  -0.849427  -1.452270   0.488613   1.459576

[1600 rows x 5 columns]


In [94]:
X = f.values
Y = dfx.iloc[:, -1].values

print(type(X))
print(type(Y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [95]:
print(X.shape)

print(Y.shape)

(1600, 5)
(1600,)


In [96]:
pd.DataFrame(X).describe()

0            1            2            3            4
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean      0.004114    -0.027604    -0.044459    -0.042408     0.012005
std       0.997338     1.021776     1.011768     1.017189     0.978654
min      -3.380125    -3.314844    -3.153118    -3.250169    -2.851707
25%      -0.647165    -0.705030    -0.706385    -0.709504    -0.615880
50%      -0.000360    -0.043769    -0.041272    -0.029756    -0.013527
75%       0.682118     0.645442     0.639130     0.646290     0.650089
max       3.287205     3.438895     3.216176     2.985410     3.321770

In [97]:
# u = np.mean(X, axis=0)
# std = np.mean(X, axis=0)
# # print(u.shape, std.shape)

In [98]:
# X = (X - u)/std

In [99]:
# df = pd.DataFrame(X)
# print(df.describe())

In [100]:
pd.DataFrame(X).describe()

0            1            2            3            4
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean      0.004114    -0.027604    -0.044459    -0.042408     0.012005
std       0.997338     1.021776     1.011768     1.017189     0.978654
min      -3.380125    -3.314844    -3.153118    -3.250169    -2.851707
25%      -0.647165    -0.705030    -0.706385    -0.709504    -0.615880
50%      -0.000360    -0.043769    -0.041272    -0.029756    -0.013527
75%       0.682118     0.645442     0.639130     0.646290     0.650089
max       3.287205     3.438895     3.216176     2.985410     3.321770

In [101]:
ones = np.ones((X.shape[0], 1))
print(ones)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [102]:
X_ = np.hstack((ones, X))
print(X_)

[[ 1.          0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [ 1.         -0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 1.          0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.          1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [ 1.         -1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [ 1.         -1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [103]:
def hypothesis(X,theta):
    return np.dot(X,theta)

def error(X,y,theta):
    e = 0.0
    y_ = hypothesis(X,theta)
    e = np.sum((y-y_)**2)
    
    return e/m
    
def gradient(X,y,theta):
    
    y_ = hypothesis(X,theta)
    grad = np.dot(X.T,(y_ - y))
    m = X.shape[0]
    return grad/m

def gradient_descent(X,y,learning_rate = 0.1,max_iters=300):
    
    n = X.shape[1]
    theta = np.zeros((n,))
    error_list = []
    
    for i in range(max_iters):
        e = error(X,y,theta)
        error_list.append(e)
        
        #Gradient descent
        grad = gradient(X,y,theta)
        theta = theta - learning_rate*grad
        
    return theta,error_list
    


In [104]:
theta,error_list = gradient_descent(X_,Y)
print(theta)

[ 4.99096674 29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]


In [106]:
y_ = []
m = X.shape[0]
for i in range(m):
    pred = hypothesis(X_[i],theta)
    y_.append(pred)
y_ = np.array(y_)

In [107]:
print(X_[17])

[ 1.         -1.04438892 -0.65623157 -0.63009787  1.13407585 -0.4478742 ]


In [108]:
def r2_score(y,y_):
    num = np.sum((y-y_)**2)
    denom = np.sum((y- y.mean())**2)
    score = (1- num/denom)
    return score*100

In [109]:
r2_score(Y,y_)

96.60939669975616

In [113]:
print(y_[5])

-134.51792086480896


In [115]:
df_test = pd.read_csv("./Datasets/Test.csv")
X_test = df_test.values

In [117]:
print(X_test.shape)

(400, 5)


In [124]:
ones_test = np.ones((X_test.shape[0], 1))
X_test_ = np.hstack((ones_test, X_test))
print(X_test_)

[[ 1.00000000e+00  1.01525387e+00  2.07620944e+00 -2.66434820e-01
  -2.41808820e+00 -9.80502790e-01]
 [ 1.00000000e+00 -3.75021204e-01  9.53184528e-01  6.26719138e-01
   7.04405750e-01 -3.55489211e-01]
 [ 1.00000000e+00 -1.02445225e+00  9.62991107e-01 -4.07942004e-01
  -1.86127383e+00  4.55201351e-01]
 ...
 [ 1.00000000e+00  5.54727647e-01  1.76824345e+00 -8.97787210e-01
  -1.19366107e+00  3.40563374e-01]
 [ 1.00000000e+00 -1.62717246e+00  8.56470994e-01 -5.65729519e-04
   6.29386649e-01  4.53382144e-01]
 [ 1.00000000e+00  1.39310499e-01  5.31597186e-01 -8.53107053e-01
   3.16920076e-02  1.71489304e+00]]


In [145]:
y_test = []
m = X_test.shape[0]
for i in range(m):
    pred = hypothesis(X_test_[i],theta)
    y_test.append(pred)
y_test = np.array(y_test)

In [146]:
print(y_test.shape)

(400,)


In [154]:
df_sub = pd.DataFrame(y_test, columns=["target"])

In [156]:
df_sub.to_csv("Sample_Submission.csv", index=True, index_label="Id")

In [150]:
print(df_sub)

              0
0    114.583689
1    118.012815
2    -21.739852
3    -43.936899
4    -95.914898
..          ...
395  -81.989000
396 -186.032535
397  125.292336
398   65.369841
399   57.059691

[400 rows x 1 columns]
